Vagrant.configure('2') do |config|
  config.vm.box = 'centos7'
  config.vm.hostname = 'localhost'

  config.vm.define :box do |box|
    box.vm.network 'private_network', :ip => '44.44.44.11'
  end

  config.vm.provision :ansible do |ansible|
    ansible.playbook = 'playbook.yml'
    ansible.extra_vars = { ansible_ssh_user: 'vagrant', vagrant: true }

    ansible.verbose = 'v'
  end
end
